broadband-modem-qmi: fix object logging with WITH_NEWEST_QMI_COMMANDS
  mm-broadband-modem-qmi.c: In function 'common_signal_info_get_quality':
  mm-broadband-modem-qmi.c:1469:21: error: 'self' undeclared (first use in this function)
           mm_obj_dbg (self, "RSSI (CDMA): %d dBm", cdma1x_rssi);
                       ^~~~
  mm-broadband-modem-qmi.c:1469:21: note: each undeclared identifier is reported only once for each function it appears in
           mm_obj_dbg (self, "RSSI (CDMA): %d dBm", cdma1x_rssi);
                       ^~~~
  mm-broadband-modem-qmi.c: In function 'process_gsm_info':
  mm-broadband-modem-qmi.c:2992:25: error: 'self' undeclared (first use in this function)
               mm_obj_dbg (self, "no GSM service reported");
                           ^~~~
  mm-broadband-modem-qmi.c: In function 'process_wcdma_info':
  mm-broadband-modem-qmi.c:3100:25: error: 'self' undeclared (first use in this function)
               mm_obj_dbg (self, "no WCDMA service reported");
                           ^~~~
  mm-broadband-modem-qmi.c: In function 'process_lte_info':
  mm-broadband-modem-qmi.c:3209:25: error: 'self' undeclared (first use in this function)
               mm_obj_dbg (self, "no LTE service reported");
                           ^~~~
  mm-broadband-modem-qmi.c: In function 'config_signal_info_ready':
  mm-broadband-modem-qmi.c:4890:21: error: 'self' undeclared (first use in this function)
           mm_obj_dbg (self, "QMI operation failed: '%s'", error->message);
                       ^~~~

Signed-off-by: Justin Standring <justin.standring@taitradio.com>
(cherry picked from commit 6ec12add1ba6625a8470ae3cf7b30cefcf28d503)