sleep-monitor-powerd: remove unused variables
  mm-sleep-monitor-powerd.c: In function ‘signal_cb’:
  mm-sleep-monitor-powerd.c:81:14: error: unused variable ‘is_about_to_suspend’ [-Werror=unused-variable]
     81 |     gboolean is_about_to_suspend;
        |              ^~~~~~~~~~~~~~~~~~~
  mm-sleep-monitor-powerd.c: In function ‘on_pd_proxy_acquired’:
  mm-sleep-monitor-powerd.c:100:11: error: unused variable ‘owner’ [-Werror=unused-variable]
    100 |     char *owner;
        |           ^~~~~