libmm-glib: Initialize result array
In mm_modem_messaging_get_supported_storages(), initialize array to avoid a
potential crash with an uninitialized value, and a build failure due to

mm-modem-messaging.c:168:24: error: 'array' may be used uninitialized in this
function [-Werror=maybe-uninitialized]
     *n_storages = array->len;

https://bugzilla.gnome.org/show_bug.cgi?id=729267