broadband-modem-qmi: avoid unused functions
Only applicable when building with WITH_NEWEST_QMI_COMMANDS.

  mm-broadband-modem-qmi.c:4741:1: error: ‘common_enable_disable_unsolicited_events_signal_strength’ defined but not used [-Werror=unused-function]
   4741 | common_enable_disable_unsolicited_events_signal_strength (GTask *task)
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mm-broadband-modem-qmi.c:4528:1: error: ‘serving_system_indication_cb’ defined but not used [-Werror=unused-function]
   4528 | serving_system_indication_cb (QmiClientNas *client,
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mm-broadband-modem-qmi.c:3468:1: error: ‘common_enable_disable_unsolicited_registration_events_serving_system’ defined but not used [-Werror=unused-function]
   3468 | common_enable_disable_unsolicited_registration_events_serving_system (GTask *task)
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mm-broadband-modem-qmi.c:2812:1: error: ‘get_serving_system_3gpp_ready’ defined but not used [-Werror=unused-function]
   2812 | get_serving_system_3gpp_ready (QmiClientNas *client,
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mm-broadband-modem-qmi.c:1652:1: error: ‘get_signal_strength_ready’ defined but not used [-Werror=unused-function]
   1652 | get_signal_strength_ready (QmiClientNas *client,

(cherry picked from commit 0f60b225a21cc69291b7783c58e8f957ff426ee4)