broadband-modem-mbim: remove unused variable
    CC       ModemManager-mm-broadband-modem-mbim.o
    mm-broadband-modem-mbim.c: In function ‘mbim_port_open_ready’:
    mm-broadband-modem-mbim.c:1581:35: error: unused variable ‘ctx’ [-Werror=unused-variable]
         InitializationStartedContext *ctx;
                                       ^~~
    cc1: all warnings being treated as errors