bearer-qmi: fix build with libqmi 1.16
The cleanup_event_report_unsolicited_events() method is only defined
when using libqmi >= 1.18.0.

    CC       ModemManager-mm-bearer-qmi.o
   <mm-1-6-with-qmi-1.16-mbim-1.14/ws/source/src/mm-bearer-qmi.c>: In function ‘reset_bearer_connection’:
   <mm-1-6-with-qmi-1.16-mbim-1.14/ws/source/src/mm-bearer-qmi.c>:1589:17: error: implicit declaration of function ‘cleanup_event_report_unsolicited_events’ [-Werror=implicit-function-declaration]
                    cleanup_event_report_unsolicited_events (self,
                    ^
   cc1: all warnings being treated as errors
   Makefile:1489: recipe for target 'ModemManager-mm-bearer-qmi.o' failed

Fixes: 068c7df4127086c051a59ca032b8e6ae911a348b