helpers: remove unnecessary `>= 0' checks on guint value
This CL removes the unnecessary `>= 0' check on `mode_val' and
`ind_val', which are both guint values extracted from a GArray with
guint values, in mm_3gpp_parse_cmer_test_response to address the
following compiler warnings:

mm-modem-helpers.c:2933:22: error: comparison of unsigned expression >=
0 is always true [-Werror,-Wtautological-compare]
        if (mode_val >= 0 && mode_val <= 3)
            ~~~~~~~~ ^  ~
mm-modem-helpers.c:2943:21: error: comparison of unsigned expression >=
0 is always true [-Werror,-Wtautological-compare]
        if (ind_val >= 0 && ind_val <= 2)
            ~~~~~~~ ^  ~