broadband-modem-qmi: fix type comparison
Only applicable when building with WITH_NEWEST_QMI_COMMANDS.

  mm-broadband-modem-qmi.c: In function ‘process_common_info’:
  mm-broadband-modem-qmi.c:2924:20: error: comparison is always false due to limited range of data type [-Werror=type-limits]
   2924 |         if (mnc[2] == 0xFF) {
        |                    ^~

(cherry picked from commit 0a5ab352e137e9c18a0c59be0533fde0bd307f03)