broadband-modem-qmi: Fix compilation error due to variable name change
otherwise we fail with:

CC       ModemManager-mm-broadband-modem-qmi.o
mm-broadband-modem-qmi.c: In function ‘modem_load_current_bands’:
mm-broadband-modem-qmi.c:1881:35: error: ‘ctx’ undeclared (first use in this function)
     if (qmi_client_check_version (ctx->client, 1, 19)) {
                                   ^
mm-broadband-modem-qmi.c:1881:35: note: each undeclared identifier is reported only once for each function it appears in

(cherry picked from commit 983c197c6b7b6c31e91bfb82c3d32a2578c39b53)