polkit: fix build when polkit enabled
This fixes the build after commit 740ce1fb26dd83459075f2d069a9da25e449dd89.

      CC       ModemManager-mm-auth-provider-polkit.o
    ../../src/mm-auth-provider-polkit.c: In function ‘authorize’:
    ../../src/mm-auth-provider-polkit.c:155:46: error: ‘AuthorizeContext’ has no member named ‘cancellable’
                                               ctx->cancellable,
                                                  ^
    Makefile:1533: recipe for target 'ModemManager-mm-auth-provider-polkit.o' failed