ublox: fix disabling of unsolicited events
The incorrect ready() method was being used while disabling, which
ended up making the parent disable not being run at all.

  ublox/mm-broadband-modem-ublox.c:1178:1: error: ‘voice_disable_unsolicited_events_ready’ defined but not used [-Werror=unused-function]
   1178 | voice_disable_unsolicited_events_ready (MMBroadbandModemUblox *self,
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~