libqcdm: use NULL instead of 0 for empty pointer
When I use clang 3.5 to build it, I got

commands.c:1444:16: error: expression which evaluates to zero treated as a
null
      pointer constant of type 'QcdmResult *' (aka 'struct QcdmResult *')
      [-Werror,-Wnon-literal-null-conversion]
        return FALSE;
               ^~~~~
./utils.h:29:15: note: expanded from macro 'FALSE'
#define FALSE ((u_int8_t) 0)
              ^~~~~~~~~~~~~~
commands.c:1464:20: error: expression which evaluates to zero treated as a
null
      pointer constant of type 'QcdmResult *' (aka 'struct QcdmResult *')
      [-Werror,-Wnon-literal-null-conversion]
            return FALSE;
                   ^~~~~
./utils.h:29:15: note: expanded from macro 'FALSE'
#define FALSE ((u_int8_t) 0)
              ^~~~~~~~~~~~~~
2 errors generated.
make[3]: *** [libqcdm_la-commands.lo] Error 1
make[3]: *** Waiting for unfinished jobs....

Below is the patch that fixes it